#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <limits.h>
#include <stdbool.h>

#include "../sequence.h"

int main() {
    printf("Testing create_random_sequence()...\n");
    srand(time(NULL));

    bool saw_max = false;
    bool saw_min = false;

    for(int size = 2; size < 100000; size += 10000) {
        for(int min = -5; min <= 5; min += 2) {
            for(int max = min + 1; max <= 100; max += 10) {
                int * array = create_random_sequence(size, min, max);

                for(int i = 0; i < size; i++) {
                    if(array[i] < min) {
                        printf("Test Failed:\n");
                        printf("Your function produced an array containing %i when the min was %i.\n", array[i], min);
                        exit(1);
                    }
                    else if(array[i] > max) {
                        printf("Test Failed:\n");
                        printf("Your function produced an array containing %i when the max was %i.\n", array[i], max);
                        exit(1);
                    }

                    if(array[i] == min) {
                        saw_min = true;
                    }
                    if(array[i] == max) {
                        saw_max = true;
                    }
                }
                free(array);
            }
        }
    }

    if(!saw_max) {
        printf("Test Failed:\n");
        printf("The max value never appeared in any of the arrays generated by your code.");
        exit(1);
    }
    if(!saw_min) {
        printf("Test Failed:\n");
        printf("The min value never appeared in any of the arrays generated by your code.");
        exit(1);
    }

    printf("All tests passed!\n");

    return 0;
}
